package eu.ciechanowiec.sling.rocket.llm;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * A single choice in a {@link ChatCompletion}.
 * <p>
 * Each choice is one unique answer or completion to a user's prompt, generated by {@link LLM}.
 * A typical response may include multiple such choices, each with its own text or content
 * and associated metadata (e.g., index, finish reason, or role). By working with multiple
 * choices, developers can view, compare, or select the most appropriate answer.
 * @param message {@link ChatMessage} associated with this choice
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Choice(ChatMessage message) {
}
